### ISSUE TITLE
Make elements hidden during the loading stage

### ISSUE THREAD

**Issue by dlzi** [jacksbox/jquery.fractionslider#2]
Hi Mario,

Why are all the elements visible outside of slider during the loading stage?
![Screen Shot 2013-04-24 at 14 51 57 PM](https://f.cloud.github.com/assets/1160818/418724/248c9d30-acb4-11e2-8a1c-8896ac56ba90.png)

Is there a way to keep them hidden? Because for slow internet speed, the loading process may take a while and seeing all the elements on that way, may got the user confused. It looks like something went wrong. Even for users on high speed internet, you still can see the elements for a few seconds, which IMO it doesn't look nice.

Any thoughts?

Cheers

**Comment by Ceiron** [comment]
its not working on me , where exactly i should put "overflow:hidden"

**Comment by Ceiron** [comment]
Nevermind i found a solution guys.

(With Jquery)

use this code

.nameofclass
{
visibility:hidden;
display:none;
}

 $(document).ready(function () {
      $('.nameofclass').css('visibility', 'visible');
 });

".nameofclass" give this classes to make slider elements invisible before plugin loads. After everything loaded succesfully jquery code will make your elements visible. Not perfect but working :)
