### ISSUE TITLE
Can't download the repo with bower

### ISSUE THREAD

**Issue by lorenaramonda** [jacksbox/jquery.fractionslider#38]
Hi,
I can't find the repo in bower packages, or better I find it but the link to github is broken.
Can you fix this?

**Comment by cytec** [comment]
just install it via git repo:

`bower install git://github.com/jacksbox/jquery.fractionslider.git` see https://bower.io/#install-packages

**Comment by lorenaramonda** [comment]
Oh thank you. In your bower json there's still a reference to the old (?) repo, i guess: https://github.com/nilsabegg/jquery.fractionslider.git
